> # Jiya Chudasama 
 [21670307021]

>   # Lab 7_1>>To create a dataframe from a dictionary and display it

In [ ]:
import pandas as pd

a={'Name':['Jiya Chudasama','Kishan Jungi','Krishaa Joshi','Honey Modha'],
  'Enrollment':[21,14,47,65]
  }
df=pd.DataFrame(a)
df

> # Lab 7_2>>To sort the DataFrame first by 'name' in ascending order

In [ ]:
import pandas as pd
import numpy as np

a={'Name':["Jiya","Subodh","Krupali","Priyanshu"],
  'Age':[16,42,42,10],
  'Education':["IT","Chemist","M.com","Fifth"]}
df=pd.DataFrame(a)

print("The native Data >>\n\n ",df)
df = df.sort_values(by=['Name', 'Age'], ascending=[True,False])
print("\n\n")
print("Sort the data frame first by ‘name’ in ascending order, then by ‘age’ in descending  order>>\n\n",df)

> # Lab 7_3 >>To delete the one specific column from the DataFrame

In [ ]:
import pandas as pd

a = {'P': ['P1', 'P2', 'P3', 'P4', 'P5'],
     'A': ['A1', 'A2', 'A3', 'A4', 'A5'],
     'N': ['N1', 'N2', 'N3', 'N4', 'N5'],
     'D': ['D1', 'D2', 'D3', 'D4', 'D5'],
     'A': ['A1', 'A2', 'A3', 'A4', 'A5'],
     'S': ['S1', 'S2', 'S3', 'S4', 'S5']}
df = pd.DataFrame(a)
print("The Removing Specific Row >>",df)


df.drop(['S'], axis=1)

> # Lab 7_4 >>To write a DataFrame to CSV file using tab separator

In [ ]:
import pandas as pd
import numpy as np
a = {'Name': ["Jess", "Kess", "Hess", "Dess"], 'Entrollment': [4, 5, 6, 7], 'SPI': [8.9, 9.9, 9,9.4]}
df = pd.DataFrame(data=a)
print("\n\n")
print("The Native DataFrame >>\n",df)

print('Data from new_file.csv file >>')
df.to_csv('new_file.csv', sep='\n', index=False)
new_df = pd.read_csv('new_file.csv')
print(new_df)